Подготовил вставку тестовых данных
WhyRocket/sql-practice pull request #14
Opened 2024-05-28 08:56 UTC by WhyRocket

2024-05-28 09:15 UTC, aleksandr-goncharov requested changes

2024-05-28 09:15 UTC, aleksandr-goncharov commented on src/7_insert_data.sql
> +('Penguin Random House', 1, 'New York', 'Broadway', '1745', 'info@penguinrandomhouse.com', '+1-800-733-3000'),
в поле phone_number поместится номер телефона в таком формате?

2024-05-28 09:15 UTC, aleksandr-goncharov commented on src/7_insert_data.sql
> +(1, 1),
я бы усложнил эти данные
например, один клиент взял бы 2 одинаковые книги
а другой клиент взял несколько разных книг

2024-05-28 09:15 UTC, aleksandr-goncharov commented on src/script_for_GPT.sql
> +CREATE DATABASE sql_practice;
зачем это в гите? в чем отличие от init скрипта?

2024-05-28 19:18 UTC, WhyRocket commented on src/7_insert_data.sql
> +('Penguin Random House', 1, 'New York', 'Broadway', '1745', 'info@penguinrandomhouse.com', '+1-800-733-3000'),
Да, ограничено ведь только максимальное число символов

2024-05-29 08:29 UTC, aleksandr-goncharov approved these changes

2024-05-29 08:30 UTC, merged