Инициализация таблиц базы данных
WhyRocket/sql-practice pull request #5
Opened 2024-05-15 18:06 UTC by WhyRocket

2024-05-16 11:22 UTC, aleksandr-goncharov requested changes

2024-05-16 11:22 UTC, aleksandr-goncharov commented on README.md
> +# sql-practice
Давай пока не будем изменять readme
Оформим его в самом конце, когда закончим работу

2024-05-16 11:22 UTC, aleksandr-goncharov commented on src/init.sql
> +    Id SERIAL PRIMARY KEY,
я совсем забыл добавить описание в ишью, прочитай его , пожалуйста

2024-05-16 11:22 UTC, aleksandr-goncharov commented on src/init.sql
> +    BookTitle CHARACTER VARYING,
не нужно ли ограничить длину этого поля? может быть 1000 символов?
помимо этого, лучше использовать название `title`, потому что и так понятно, что это название книги по названию таблицы

2024-05-16 11:22 UTC, aleksandr-goncharov commented on src/init.sql
> +    YearOfPublishing DATE,
давай переименуем в `publishing_year`, чтобы избежать слова `of`

2024-05-16 11:22 UTC, aleksandr-goncharov commented on src/init.sql
> +    ISBN CHARACTER(17),
почему тут ограничение именно в 17 символов?

2024-05-16 11:22 UTC, aleksandr-goncharov commented on src/init.sql
> +    PublisherId SERIAL,
не создано ограничение внешнего ключа
видимо потому, что еще нет таблицы publisher
но в любой случае ознакомься с ограничениями, которые можно добавлять https://postgrespro.ru/docs/postgresql/9.5/ddl-constraints

2024-05-16 11:22 UTC, aleksandr-goncharov commented on src/init.sql
> +    NumberOfBooks SMALLINT
тут давай тоже избавимся от `of`

2024-05-16 11:22 UTC, aleksandr-goncharov commented on src/init.sql
> +    Id SERIAL,
нет ограничения первичного ключа

2024-05-16 11:22 UTC, aleksandr-goncharov commented on src/init.sql
> +    Genre CHARACTER VARYING(20)
тут хорошо бы назвать столбец `name`
т.е. "Наименование жанра"

2024-05-16 11:22 UTC, aleksandr-goncharov commented on src/init.sql
> +CREATE TABLE book_genre
таблицы давай называть во множественном числе, т.е. `book_genres`
"Жанры книг"

2024-05-16 11:22 UTC, aleksandr-goncharov commented on src/init.sql
> +    IdGenre SERIAL REFERENCES genres (Id) ON DELETE CASCADE,
тут у меня два вопроса:
1) почему использован тип данных serial?
2) почему указано каскадное удаление? действительно ли это наилучшее поведение и почему? рассматривал ли вариант RESTRICT?

2024-05-16 11:25 UTC, aleksandr-goncharov requested changes

2024-05-16 11:25 UTC, aleksandr-goncharov commented on src/init.sql
> +CREATE TABLE books
давай называть файлики с цифрой в начале:
"1_init.sql"
далее будут файлы "2_...sql" и т.д.
таким образом мы не потеряем последовательность применения скриптов

2024-05-16 11:33 UTC, WhyRocket commented on src/init.sql
> +    ISBN CHARACTER(17),
Потому что форма ISBN-13 подразумевает использование 13 цифр, 3 тире и пробел/тире

2024-05-17 07:48 UTC, WhyRocket commented on src/init.sql
> +    Genre CHARACTER VARYING(20)
Я так и хотел, но как я понял, это ключевое слово какое-то

2024-05-17 07:53 UTC, WhyRocket commented on src/init.sql
> +    IdGenre SERIAL REFERENCES genres (Id) ON DELETE CASCADE,
Заменю SERIAL на INTEGER, так как нет необходимости автоинкрементирования

Для жанра, я не уверен в том, какое именно поведение нужно указать, согласен, что каскадное удаление в данном случае не подходит. Наверное, лучше будет SET NULL. Хотя зачем вообще библиотеке удалять жанры

2024-05-17 09:50 UTC, aleksandr-goncharov requested changes

2024-05-17 09:50 UTC, aleksandr-goncharov commented on README.md
> +Данный репозиторий хранит базу данных библиотеки, созданную по следующему техническому заданию:
readme не убрали из ПР

2024-05-17 09:50 UTC, aleksandr-goncharov commented on src/1_init.sql
> +    publisher_id SERIAL,
почему у будущего внешнего ключа тип данных serial?

2024-05-17 09:50 UTC, aleksandr-goncharov commented on src/1_init.sql
> +    genre VARCHAR(20)
не очень красиво будет обращаться в названию жанра:
`library.genres.genre`
гораздо лучше
`library.genres.name`

2024-05-17 09:50 UTC, aleksandr-goncharov commented on src/1_init.sql
> +    id SERIAL PRIMARY KEY,
предлагаю во всех таблицах, где необходимо расставить ограничение NOT NULL
https://postgrespro.ru/docs/postgresql/9.6/ddl-constraints#idp7
по умолчанию, столбцы допускают значение NULL
но, к примеру, на столбец title очевидно нужно ограничение NOT NULL, потому что какой смысл добавлять книгу, если у нее нет названия

2024-05-17 09:50 UTC, aleksandr-goncharov commented on src/1_init.sql
> +    id_genre INTEGER REFERENCES genres (Id) ON DELETE SET NULL,
почему выбрано поведение SET NULL при удалении жанра?
также для этой таблицы не хватает первичного ключа
добавлять отдельный столбец ID можно, но как будто бы излишне
может быть рассмотреть вариант составного первичного ключа?

2024-05-17 09:53 UTC, aleksandr-goncharov requested changes

2024-05-17 09:53 UTC, aleksandr-goncharov commented on src/1_init.sql
> +    isbn CHAR(17),
взято из документации постгреса для сивольных типов данных:
`на деле char(n) обычно оказывается медленнее остальных типов из-за большего размера данных и более медленной сортировки. В большинстве случаев вместо него лучше применять text или character varying.`
давай заменим его на varchar

2024-05-17 09:55 UTC, aleksandr-goncharov commented on src/1_init.sql
> +    genre VARCHAR(20)
если название столбца совпадает с некоторым ключевым словом, то это ключевое слово нужно экранировать, чтобы постгрес воспринимал name, как название столбца, а не как ключевое слово
экранирование делается с помощью кавычек:
`name VARCHAR(20)`

2024-05-17 09:58 UTC, aleksandr-goncharov commented on src/init.sql
> +    IdGenre SERIAL REFERENCES genres (Id) ON DELETE CASCADE,
я согласен, что жанры удалять вряд ли будет необходимость
но есть пользователь БД случайно решил удалить жанр, то твой SET NULL затрет жанр у тысяч книг и жанр будет удален
я бы использовал RESTRICT
до тех пор, пока на жанр ссылаются некоторые книги, такой жанр будет нельзя удалить

2024-05-17 09:59 UTC, aleksandr-goncharov commented on src/init.sql
> +    IdGenre SERIAL REFERENCES genres (Id) ON DELETE CASCADE,
для книг указано CASCADE - тут согласен, при удалении книги из БД мы удалим всю информацию о жанрах этой книги

2024-05-17 09:59 UTC, aleksandr-goncharov commented on src/init.sql
> +    IdGenre SERIAL REFERENCES genres (Id) ON DELETE CASCADE,
@WhyRocket

2024-05-17 10:00 UTC, aleksandr-goncharov commented on src/1_init.sql
> +    id_genre INTEGER REFERENCES genres (Id) ON DELETE SET NULL,
по поводу SET NULL написал свое мнение в предыдущем комменте

2024-05-17 12:04 UTC, WhyRocket commented on README.md
> +Данный репозиторий хранит базу данных библиотеки, созданную по следующему техническому заданию:
Давай я его просто очищу пока что

2024-05-19 15:44 UTC, aleksandr-goncharov requested changes
Просьба, не добавлять пока что больше новых таблиц, а то ПР разрастается

2024-05-19 15:44 UTC, aleksandr-goncharov commented on src/1_init.sql
> +CREATE TABLE library.lib_customers
Ксли таблица связывает книги и клиентов, то лучше назвать таблицу customer_books (по названию обоих таблиц

2024-05-19 15:44 UTC, aleksandr-goncharov commented on src/1_init.sql
> +    id_book INTEGER REFERENCES books (id) ON DELETE CASCADE,
Я бы здесь тоже сделал рестрикт
А то получится, что можно удалить книги, даже если какой-то клиент ее взял на руки
И мы потеряем информацию о том, что эту книги кто-то взял

2024-05-19 15:44 UTC, aleksandr-goncharov commented on src/1_init.sql
> +    PRIMARY KEY (id_customer, id_book)
Получается что клиент не может взять несколько одинаковых книг? Например, две копии одной книги (для себя и для своего сына тоже)

2024-05-19 15:44 UTC, aleksandr-goncharov commented on src/1_init.sql
> +    building_number SMALLINT NOT NULL,
В адресе всегда используем varchar, даже для но ера дома
Потому что номер дома может быть 8/3к5

2024-05-20 06:14 UTC, aleksandr-goncharov approved these changes

2024-05-20 06:14 UTC, merged