Написал скрипты для исправления допущенных ошибок
WhyRocket/sql-practice pull request #9
Opened 2024-05-21 13:48 UTC by WhyRocket

2024-05-21 14:13 UTC, aleksandr-goncharov requested changes

2024-05-21 14:13 UTC, aleksandr-goncharov commented on src/2_bug_fix.sql
> +RENAME TO books_genres
точки с запятой нет в конце

и по правилам английского языка, если тебе нужно сделать множественное число для словосочетания из двух существительных, то окончание s нужно добавлять только в последнему слову)
т.е. для словосочетания ""жанры книг" правильным будет вариант "book_genres", а не "books_genres"

2024-05-21 14:13 UTC, aleksandr-goncharov commented on src/2_bug_fix.sql
> +RENAME TO countrys;
тут должно быть countries

2024-05-21 14:13 UTC, aleksandr-goncharov commented on src/2_bug_fix.sql
> +ALTER TABLE library.book_genres
давай переименуем файл, ""bug fixes" - очень общее название, так можно назвать практически все что угодно
лучше добавить два файла:
2_rename_tables
3_add_fk

2024-05-23 16:00 UTC, WhyRocket commented on src/2_bug_fix.sql
> +RENAME TO books_genres
Хорошо. Я так сделал, чтобы явно указать на связанные таблицы

2024-05-24 06:24 UTC, aleksandr-goncharov approved these changes

2024-05-24 06:24 UTC, merged